version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "9092:9092"

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    ports:
      - "5432:5432"